### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by micw** [ghedo/pflask#29]
Hi, I wanted to give it a try but I get:

```
[mwyraz@mw-t470s ✓ ~/git/pflask $ ./bootstrap.py 
Downloading http://waf.io/pub/release/waf-1.8.6...
Checksum verified.
[mwyraz@mw-t470s ✓ ~/git/pflask $ ./waf configure
Traceback (most recent call last):
  File "/home/mwyraz/git/pflask/.waf3-1.8.6-815b991931c187cd7c4e2bcfeb5f4a5d/waflib/Node.py", line 293, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mwyraz/git/pflask/.waf3-1.8.6-815b991931c187cd7c4e2bcfeb5f4a5d/waflib/Scripting.py", line 103, in waf_entry_point
    run_commands()
  File "/home/mwyraz/git/pflask/.waf3-1.8.6-815b991931c187cd7c4e2bcfeb5f4a5d/waflib/Scripting.py", line 160, in run_commands
    parse_options()
  File "/home/mwyraz/git/pflask/.waf3-1.8.6-815b991931c187cd7c4e2bcfeb5f4a5d/waflib/Scripting.py", line 133, in parse_options
    Context.create_context('options').execute()
  File "/home/mwyraz/git/pflask/.waf3-1.8.6-815b991931c187cd7c4e2bcfeb5f4a5d/waflib/Options.py", line 141, in execute
    super(OptionsContext,self).execute()
  File "/home/mwyraz/git/pflask/.waf3-1.8.6-815b991931c187cd7c4e2bcfeb5f4a5d/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/mwyraz/git/pflask/.waf3-1.8.6-815b991931c187cd7c4e2bcfeb5f4a5d/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/home/mwyraz/git/pflask/wscript", line 19, in options
    opt.load('compiler_c')
  File "/home/mwyraz/git/pflask/.waf3-1.8.6-815b991931c187cd7c4e2bcfeb5f4a5d/waflib/Context.py", line 89, in load
    fun(self)
  File "/home/mwyraz/git/pflask/.waf3-1.8.6-815b991931c187cd7c4e2bcfeb5f4a5d/waflib/Tools/compiler_c.py", line 36, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/home/mwyraz/git/pflask/.waf3-1.8.6-815b991931c187cd7c4e2bcfeb5f4a5d/waflib/Context.py", line 296, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/home/mwyraz/git/pflask/.waf3-1.8.6-815b991931c187cd7c4e2bcfeb5f4a5d/waflib/Node.py", line 342, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/mwyraz/git/pflask/.waf3-1.8.6-815b991931c187cd7c4e2bcfeb5f4a5d/waflib/Node.py", line 342, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration

**Comment by micw** [comment]
I installed waf and python-sphinx from system (arch linux) and used the recent version (2.0.20). Seems to be an issue with python 3.

Now I get:
```
[17/19] Linking build/pflask
/usr/bin/ld: src/cgroup.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
/usr/bin/ld: src/dev.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
/usr/bin/ld: src/machine.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
/usr/bin/ld: src/mount.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
/usr/bin/ld: src/netif.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
/usr/bin/ld: src/nl.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
/usr/bin/ld: src/path.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
/usr/bin/ld: src/pflask.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
/usr/bin/ld: src/printf.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
/usr/bin/ld: src/pty.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
/usr/bin/ld: src/sync.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
/usr/bin/ld: src/user.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
/usr/bin/ld: src/util.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: multiple definition of `use_syslog'; src/capabilities.c.1.o:/home/mwyraz/git/pflask/build/../src/printf.h:42: first defined here
collect2: error: ld returned 1 exit status
```

**Comment by micw** [comment]
Got it built using "extern" for that variable (like in https://stackoverflow.com/questions/11072244/c-multiple-definitions-of-a-variable) - no idea what effect it has ^^
